### ISSUE TITLE
Incorrect Toast Message Displayed for Blocked/Disabled User Access Attempt

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/launchpad#103]
## Expected behavior
The toast message should accurately convey that the user account is blocked or disabled, providing clear information to the user about the reason for denied access.

## Steps to reproduce the issue
Block or disable a user account within the application.
Attempt to access the application using the blocked or disabled user account credentials.
Observe the toast message displayed upon denied access.

## Environment details
- App version: v1.6.0
- Testing Environment: UAT

## Additional information
![Screenshot 2024-03-12 at 1 00 43 PM](https://github.com/hotwax/user-management/assets/158989293/0fba7a02-bc8c-446c-991a-fe75482e3ee0)

**Comment by ymaheshwari1** [comment]
@dt2patel Sir, Currently we are thinking of updating the message to `Sorry, either your login details are incorrect, or your account has been disabled or blocked. Please try again or contact administrator.`. As its difficult to identify from the api response that whether the credentials are wrong or account is blocked.

**Comment by dt2patel** [comment]
Let's work on improving the API response. @ymaheshwari1 we can discuss in person

**Comment by dt2patel** [comment]
UI for blocked user will be handled in this issue:
https://github.com/hotwax/dxp-components/issues/204
