### ISSUE TITLE
Add entry for the "Atp" app in the dashboard replacing the "Threshold management" app

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/launchpad#113]
## What is the motivation for adding/enhancing this feature?

Currently our dashboard shows entry for the threshold management app. Instead we want to show entry of the newly developed "Atp" app in the dashboard.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine. Hence, closing it.
