### ISSUE TITLE
Implement Password Reset Functionality

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#124]
## What is the motivation for adding/enhancing this feature?
Currently, users are unable to reset their passwords if forgotten them. This leads to user inconvenience and potential account lockouts.

## Proposed Solution:
- Implement a password reset functionality that allows users to recover their accounts by getting a reset password link in their registered email.

## Acceptance Criteria:
- Users can successfully reset their passwords via a dedicated password reset flow.
- Reset functionality is accessible from the login screen.

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
UI [link](https://www.figma.com/design/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?node-id=29064-69902&t=tXBfxqyXuBD2jcYF-1)

**Comment by dt2patel** [comment]
Closing ticket, UI and implementation for this will be handled here:
https://github.com/hotwax/dxp-components/issues/204
