### ISSUE TITLE
Application Attempts Login with Expired Token After User Logout in Lauchpad

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#36]
## Current behavior
Despite successfully logging out, when the user attempts to log in an application, it continues to make multiple futile attempts to authenticate using the expired token. 

## Expected behavior
Following a user logout, the application should recognize the invalidated token and immediately prompt the user for fresh login credentials. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by k2maan** [comment]
Closing as fixed with #37
