### ISSUE TITLE
Pre-filled Instance Details Not Accepted Upon Token Expiration

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#40]
## Current behavior
When attempting to log in to Launchpad after authentication token is expired, the pre-filled instance details on the login page are not being accepted and causing error.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
Behavior no longer recreated, will make new issue if this still happens
