### ISSUE TITLE
Remove hover CSS from Mobile

### ISSUE THREAD

**Issue by dt2patel** [hotwax/launchpad#5]
Touch devices shouldn't have hover css because they cannot differentiate between a touch, click and hover.

**Comment by ahmedsilat44** [comment]
Could a possible fix be a simple media query where the hover effect only happens on big screens ?

**Comment by dt2patel** [comment]
@ahmedsilat44 yep, that's valid

**Comment by ahmedsilat44** [comment]
> @ahmedsilat44 yep, that's valid

Could you assign the issue to me and I can work on this. Thanks 😄

**Comment by ahmedsilat44** [comment]
I haven't worked with this library so I'll read the docs and implement the changes if I can.

**Comment by dt2patel** [comment]
The CSS for hover isn't specific to the library, if that helps. It's all written in the Home.Vue file
