### ISSUE TITLE
Show Frequently Used Apps for Quick Selection

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#56]
## What is the motivation for adding/enhancing this feature?
To enhance user experience and efficiency, we should prioritizing frequently used apps at the top of the list for quick selection. This feature will enable users to access their most commonly used apps more easily and reduce the time spent searching for them.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
Please refer this UI: https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?type=design&node-id=28820%3A145475&mode=design&t=zbJkwXeJLw8jFnxt-1

**Comment by SakshiKant** [comment]
can you assign me this issue

**Comment by k2maan** [comment]
Sure @SakshiKant go ahead
