### ISSUE TITLE
Remove Unnecessary "Please fill details" Toast on Pre-filled Login Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#58]
## Expected behavior
Currently, when users are redirected to the login page and their credentials are already pre-filled in the input fields, they receive an unnecessary toast notification prompting them to input credentials. This toast is confusing and redundant, as the credentials are already provided.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
need to check if this is still happening

**Comment by ymaheshwari1** [comment]
This issue occurs mainly on the first time when app becomes unauthorized and logouts.

**Comment by dt2patel** [comment]
@Adameddy26 can you please review this and attach a jam link for what exactly is happening here.

**Comment by Adameddy26** [comment]
Issue is replicated at my end multiple times but the toast message is not getting captured in the JAM video. Therefore, mentioning the steps here.

Steps to Replicate - 
1. Log in the App with a user.
2. Open the login URL in other window.
3. Here, log in with same user and then logout from the App.
4. Go back to first window and logout from the App.
5. Click on Login button in the first window to observe the issue. 

@ravilodhi Please connect with me in case of any doubt.

**Comment by Adameddy26** [comment]
Checked it and found that it is working fine. May be it got fixed in impact of some other issue fix. Therfore, closing this issue.
