### ISSUE TITLE
Implement Quick Access to OMS on Home Page for Logged-in Users

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#59]
## What is the motivation for adding/enhancing this feature?
Currently, accessing the Order Management System (OMS) requires users to navigate through multiple pages, which can be time-consuming and inefficient. 

Implement a dedicated section or button on the Home page that provides seamless access to the OMS for users who are already logged in. 

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Saiyam-Kumawat** [comment]
would you please assign this issue to me

**Comment by k2maan** [comment]
Sure @Saiyam-Kumawat go ahead

**Comment by dt2patel** [comment]
![Image](https://github.com/hotwax/launchpad/assets/60128132/7f8f2a1a-0bf7-49dc-a401-4bdf03624146)

Mockup
