### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Santhusha-bit** [hotwax/launchpad#6]
## What is the motivation for adding/enhancing this feature?

Having a good [README.md](https://github.com/hotwax/launchpad#readme), It's easy to new developers to get familiar with the project

## What are the acceptance criteria?

- [ ] About section
- [ ] Get Started section
- [ ] Contributing section

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Additional information

Refer other Readme.md files in similar projects

**Comment by dt2patel** [comment]
Are you interested in picking this issue? You can take examples from our other repositories

**Comment by Santhusha-bit** [comment]
Yes. I'll start working on this
