### ISSUE TITLE
Add Spinner Inside the Logout Button

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#60]
## What is the motivation for adding/enhancing this feature?
 would like to propose an enhancement to the user interface by adding a spinner inside the logout button. Currently, when users click the logout button, it can be unclear whether their request is being processed. By integrating a spinner directly inside the button, users will have a visual cue that their action is in progress. This small but impactful change can significantly improve the user experience.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by HarshalMahajan0110** [comment]
please assign me?

**Comment by k2maan** [comment]
Sure @HarshalMahajan0110 go ahead

**Comment by ymaheshwari1** [comment]
I think instead of adding the spinner inside the logout button we can display a loader and block the whole screen, as once initiating logout request user should not be allowed to do anything until logout completes.

**Comment by Adameddy26** [comment]
Verified the changes and are working fine. Hence, closing this ticket.
