### ISSUE TITLE
Enhance Log Out API Handling for System Downtime or Termination

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/launchpad#84]
## What is the motivation for adding/enhancing this feature?
Currently, our system does not adequately handle log out requests when the system is experiencing downtime or has been terminated. To improve user experience and provide appropriate feedback during such scenarios, we propose enhancing the log out API to gracefully handle situations where the system is unavailable.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
Current handling ensures that if user is logging out and server is unavailable, they still are able to logout of their current app. Closing issue
